# Generated by Django 5.1.4 on 2024-12-14 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("biography", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("year_publication", models.PositiveIntegerField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("fiction", "Fiction"),
                            ("non_fiction", "Non-fiction"),
                            ("textbook", "Textbook"),
                        ],
                        max_length=100,
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("publisher", models.CharField(max_length=100)),
                ("cover_image", models.ImageField(upload_to="covers/")),
                ("book_file", models.FileField(upload_to="books/")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.author"
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("title", "author", "year_publication", "publisher")
                },
            },
        ),
    ]
